### ISSUE TITLE
Error while launching the game.

### ISSUE THREAD

**Issue by Calolardo** [huskcasaca/effortless-fabric#3]
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod effortless
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more

**Comment by huskcasaca** [comment]
The issue of `accessWidener` is already fixed in version `1.2.1`. Can you try version `1.3.0`?

**Comment by huskcasaca** [comment]
Oh, the file was automatically uploaded by a gradle plugin. I'm not able to customize its name for now.
