### ISSUE TITLE
Cannot start minecraft while only effortless mod and fabric api installed

### ISSUE THREAD

**Issue by ZowuZio** [huskcasaca/effortless-fabric#4]
windows 10, Minecraft 1.18.2, with only this mod and fabric api in mod document.

[19:36:16] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.9
[19:36:16] [main/INFO]: Loading 49 mods:
	- effortless 1.3.0
	- fabric-api 0.59.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric-api
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric-api
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric-api
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric-api
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric-api
	- fabric-containers-v0 0.1.23+d7c144a860 via fabric-api
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric-api
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric-api
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
	- fabric-data-generation-api-v1 3.0.1+9fcb91d260 via fabric-api
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric-api
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric-api
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric-api
	- fabric-events-lifecycle-v0 0.2.19+d7c144a860 via fabric-api
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
	- fabric-item-api-v1 1.5.2+17cbbd4360 via fabric-api
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric-api
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric-api
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric-api
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric-api
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric-api
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric-api
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric-api
	- fabric-models-v0 0.3.6+d7c144a860 via fabric-api
	- fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric-api
	- fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric-api
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric-api
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric-api
	- fabric-registry-sync-v0 0.9.10+0d9ab37260 via fabric-api
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric-api
	- fabric-renderer-indigo 0.5.3+41a02c8a60 via fabric-api
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric-api
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric-api
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric-api
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric-api
	- fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric-api
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric-api
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric-api
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
	- fabricloader 0.14.9
	- java 18
	- minecraft 1.18.2
[19:36:16] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod effortless
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.9.jar:?]
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285) ~[access-widener-2.1.0.jar:?]
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84) ~[access-widener-2.1.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439) ~[fabric-loader-0.14.9.jar:?]
	... 3 more

**Comment by ZowuZio** [comment]
With newest version that uploaded hours ago with unchanged version number, this issue seems to be solved.
